# Generated by Django 3.2.9 on 2021-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20211104_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.IntegerField(max_length=50),
        ),
    ]
