# Generated by Django 3.2.9 on 2021-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_company_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.IntegerField(),
        ),
    ]
