# Generated by Django 3.2.9 on 2021-11-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_company_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='createdBy',
        ),
    ]
